'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { toast } from 'sonner'
import RoadmapDisplay from '@/components/ai/RoadmapDisplay'
import RiskCard from '@/components/ai/RiskCard'

export default function RoadmapPage() {
    const [loading, setLoading] = useState(false)
    const [data, setData] = useState<any>(null)

    const fetchRoadmap = async () => {
        setLoading(true)
        try {
            const res = await fetch('/api/ai-roadmap', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    reportType: 'roadmap',
                    inputData: { platform: 'youtube', audienceSize: 10000, monthlyReach: 50000 },
                    simulationResult: { scenario: 'Realistic', totalRevenue: 15000 }
                })
            })
            const json = await res.json()
            if (!res.ok) throw new Error(json.error)
            setData(json)
        } catch (err: any) {
            toast.error(err.message || 'Error fetching roadmap')
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="p-4 md:p-8 max-w-4xl mx-auto space-y-6">
            <div>
                <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
                    AI Roadmap <Badge className="bg-gradient-to-r from-purple-500 to-pink-500 text-white border-0 shadow-sm">PRO</Badge>
                </h1>
                <p className="text-zinc-500 mt-2">Your month-by-month strategic action plan generated by AI.</p>
            </div>

            {!data ? (
                <Card className="border-dashed border-2">
                    <CardContent className="flex flex-col items-center justify-center h-64 space-y-4">
                        <p className="text-zinc-500 text-center max-w-md">Run a simulation first, then generate a custom AI roadmap tailored to your numbers.</p>
                        <Button onClick={fetchRoadmap} disabled={loading} className="bg-purple-600 hover:bg-purple-700 text-white">
                            {loading ? 'Generating Strategy...' : 'Generate AI Roadmap'}
                        </Button>
                    </CardContent>
                </Card>
            ) : (
                <>
                    <RiskCard data={{
                        risks: [
                            { type: "Platform Dependency", level: "High", description: "You are solely reliant on YouTube for revenue.", mitigation: "Start an email newsletter next month to own your audience." }
                        ]
                    }} />
                    <div className="mt-8">
                        <h3 className="text-xl font-semibold mb-6">Your Strategic Plan</h3>
                        <RoadmapDisplay data={data?.roadmap || []} />
                    </div>
                </>
            )}
        </div>
    )
}
